artifact_location: file:///C:/Users/dhvani/OneDrive/Desktop/Labmentix/Real%20Estate%20Investment/mlruns/0
creation_time: 1764763393374
experiment_id: '0'
last_update_time: 1764763393374
lifecycle_stage: active
name: Default
